# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:16.14.0

        environment:
          SKIP_PREFLIGHT_CHECK: 'true'
          GENERATE_SOURCEMAP: 'false'
          NODE_OPTIONS: '--max-old-space-size=4096'

    working_directory: ~/web

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            #https://support.circleci.com/hc/en-us/articles/115015426888-Clear-project-dependency-cache
            - web-{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
            - web-{{ .Environment.CACHE_VERSION }}-dependencies-
      - run:
          command: |
            while true; do
              sleep 5
              # NOTE: on MacOS, the f argument is not supported.
              # In this case, you can drop the f argument instead.
              ps auxwwf
              echo "======"
            done
          background: true

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: build packages
          command: yarn lerna:prepublish --concurrency=1

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run linter
          command: yarn lint

      - run:
          name: Run test with coverage
          command: yarn test --verbose --collectCoverage=true --forceExit --detectOpenHandles --maxWorkers=2

      - run:
          name: upload coverage to coveralls
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

