[template]
src = "config.js.tmpl"
dest = "/usr/src/web/config.js"
keys = [
    "/react/app/backend/active",
    "/react/app/disable/login/protection",
    "/react/app/domain/name",
    "/react/app/enable/opensrp/oauth",
    "/react/app/express/oauth/get/state/url",
    "/react/app/express/oauth/logout/url",
    "/react/app/keycloak/api/base/url",
    "/react/app/keycloak/logout/url",
    "/react/app/navbar/brand/img/src",
    "/react/app/opensrp/access/token/url",
    "/react/app/opensrp/api/base/url",
    "/react/app/opensrp/authorization/url",
    "/react/app/opensrp/client/id",
    "/react/app/opensrp/logout/url",
    "/react/app/fhir/api/base/url",
    "/react/app/opensrp/user/url",
    "/react/app/website/name",
    "/react/app/action/uuid/namespace",
    "/react/app/plan/uuid/namespace",
    "/react/app/enable/teams/assignment/module",
    "/react/app/default/home/mode",
    "/react/app/enable/language/switcher",
    "/react/app/supported/languages",
    "/react/app/enable/inventory",
    "/react/app/project/language/code",
    "/react/app/language/code",
    "/react/app/enable/form/configuration",
    "/react/app/enable/product/catalogue",
    "/react/app/default/plan/id",
    "/react/app/default/plan/duration/days",
    "/react/app/date/format",
    "/react/app/main/logo/src",
    "/react/app/plan/assignment/at/geo/level",
    "/react/app/task/generation/status",
    "/react/app/default/plan/version",
    "/react/app/default/activity/duration/days",
    "/react/app/opensrp/oauth/scopes",
    "/react/app/enable/locations",
    "/react/app/enable/teams",
    "/react/app/enable/plans",
    "/react/app/enable/card/support",
    "/react/app/user/form/hidden/fields",
    "/react/app/user/form/rendered/fields",
    "/react/app/opensrp/oauth/state",
    "/react/app/filter/by/parent/id",
    "/react/app/defaults/table/page/size",
    "/react/app/enable/fhir/care/team",
    "/react/app/keycloak/users/page/size",
    "/react/app/opensrp/roles",
    "/react/app/disable/team/member/reassignment",
    "/react/app/user/form/render/fields",
    "/react/app/pagination/size",
    "/react/app/enable/server/settings",
    "/react/app/opensrp/api/v2/base/url",
    "/react/app/opensrp/web/version",
    "/react/app/opensrp/sentry/config/json",
    "/react/app/enable/fhir/locations",
    "/react/app/fhir/root/location/identifier",
    "/react/app/enable/quest"
]
